### ISSUE TITLE
How do you use multiple GPUs on single node when writing own algorithm?

### ISSUE THREAD

**Issue by user895v** [gunrock/essentials#111]
Hi, my question is basically what title says. 
Do you write the same piece of code that you write for single GPU and then just specify that you want to use multiple GPUs instead of single?

**Comment by neoblizz** [comment]
> specify that you want to use multiple GPUs instead of single?

Correct, that's the goal. The actual algorithm is not intended to change, however, the data allocated must be multi-GPUs supported. I was working on a multi-GPU vector (kind of like `std::vector`) to allow this, and if you use that + multiple GPU contexts (which you can think of your GPUs device ids), you shouldn't have to change the algorithm at all.

The idea going forward (and this is work-in-progress) is to enable multi-GPU behind the operators, so the actual algorithm at the user level remains the same.
