### ISSUE TITLE
How does advance_direction_t affect adanvce operator?

### ISSUE THREAD

**Issue by user895v** [gunrock/essentials#131]
Hello, I am a little bit confused how **advance_direction_t** affects advance operator. As I understand it **advance** operator visits every neighbor of every vertex in current frontier. Based on return value of user specified function given neighbor will be added to new frontier or it will not be added.

Example: Given directed graph **G = (V,E)** with **V = {1,2,3,4}**, **E = {(1,2), (1,3), (4,1)}**
- If my current frontier contains vertex 1 and I define flag **advance_direction_t::forward** then vertex 2 and 3 will be visited.
- If my current frontier contains vertex 1 and I define flag **advance_direction_t::backward** then vertex 4 will be visited.

Is this right?

**Comment by neoblizz** [comment]
Hey! Your understanding is not entirely correct. The `forward` is a push-based traversal, where you go from source to destination vertices, as you mentioned. `backward` will attempt to do from neighbors to given source vertex. The resultant frontier is the same (vertex 2 and 3 in your example). You just pull from all vertices with a bitmask, such that only the vertices in the mask and the frontier "pass" the traversal.

This is based on the push-pull traversal of BFS presented in this paper: [DOBFS by  Scott Beamer](http://www.scottbeamer.net/pubs/beamer-sc2012.pdf).

In `essentials`, the direction is a work-in-progress that we want to enable for all algorithms. You can see what push vs. pull might look like for SpMV example: https://github.com/gunrock/essentials/blob/master/include/gunrock/algorithms/spmv.hxx#L61-L132

**Comment by neoblizz** [comment]
[More on push-pull](https://escholarship.org/content/qt021076bn/qt021076bn.pdf?t=pam9cu)... ![image](https://user-images.githubusercontent.com/9790745/161900163-a05746d9-2c66-472c-9d04-cc825c380182.png)

**Comment by user895v** [comment]
Thank you for your answer. I would like to perform BFS on transposed graph **G** without actually transposing it. My initial thought was that I would use advance operator with flag **advance_direction_t::backward** but as it turns out it works different than I thought. Do you any idea how to transpose graph in essentials or even better perform some algorithm on transposed graph without actually transposing it?

**Comment by neoblizz** [comment]
That's a great question! The easiest way to do this is to take a Compressed Sparse Row (CSR) format graph and store it in the Compressed Sparse Column (CSC) format instead. For graphs that are stored as CSR representation have identical format/memory layout as the CSC sparse representation of its transpose.

That way, you can potentially use all the internals without really changing anything to "access" things as transposed.

If you're really opposed to actually transposing it, the operators need to support this, which is not part of the library right now. In practice, it would most likely be implemented as an on-the-fly CSR -> CSC conversion, or just stored in CSC format under the `graph_t` struct ahead of time (as explained above). Either way, there is some sort of conversion happening.

**Comment by neoblizz** [comment]
The `backward` advance actually does take advantage of this property of CSR/CSC. It just needs that extra bits of a bit-frontier to make sure only certain things "pass" the traversal, as described in the papers above. If you removed that check, and just performed advance on a CSC, it would function as you intend it to (on a transposed graph).

**Comment by user895v** [comment]
Amazing, this helps me a lot!
