### ISSUE TITLE
betweenness centrality

### ISSUE THREAD

**Issue by neoblizz** [gunrock/essentials#39]

**Comment by bkj** [comment]
https://github.com/bkj/essentials/blob/dev/bc/include/gunrock/applications/bc.hxx

AFAICT this gives the same results as Gunrock (though I need to test a little more). 

I couldn't / haven't yet figured out exactly how the Gunrock implementation is working, so the backwards pass in this implementation is slightly different.  I think you should be able to traverse the graph from the leaf nodes of the BFS computed in the forward pass, but I'm unclear on how Gunrock was doing this.  

Right now, the backwards pass checks every edge in the graph and checks if they're at the right depth of the BFS tree -- so there's some unnecessary work.  Open to any suggestions on how to improve this.

I have an implementation that does the backwards traversal, but the conditions in the backwards operator are different from Gunrock, which gives me pause.  Also, in that implementation I have to call `uniquify`, which seems suboptimal.
