### ISSUE TITLE
SSSP bug w/ directed graph

### ISSUE THREAD

**Issue by bkj** [gunrock/essentials#9]
Seems to be a bug in SSSP for when nodes have zero out-degree:

```
$ echo "%%MatrixMarket matrix coordinate pattern general
5 5 4
1 2
1 3
1 4
1 5" > bug.mtx

$ ./bin/sssp bug.mtx
```

gets stuck in an infinite loop.

**Comment by bkj** [comment]
I think you can fix by changing `remove_completed_paths` to
```c++
auto remove_completed_paths = [G, visited, iteration] __host__ __device__(
                                  vertex_t const& vertex) -> bool {
  
  if (vertex == std::numeric_limits<vertex_t>::max()) return false;
  if (visited[vertex] == iteration)                   return false;
  
  visited[vertex] = iteration;
  return G->get_number_of_neighbors(vertex) > 0;
};
```
but -- should nodes w/ zero degree _always_ be removed from the frontier?  So should this maybe go into the advance / filter internals?

I believe `gunrock/gunrock` does not have this same infinite-loop bug, so maybe we handle it the same way it was handled there.

**Comment by neoblizz** [comment]
Adding ontop of this, `bips98_606.mtx` results in an illegal error. Idk why.

**Comment by bkj** [comment]
I can take a look at `bips98_606.mtx` and try to figure out what's going wrong.

**Comment by neoblizz** [comment]
Negative weights are still an issue, but I am marking this solved for rest of the highlighted bugs: https://github.com/gunrock/essentials/commit/0fecfe5d6fd49de52dc784ca38763754fdf8bddc
